# CODED BY SAM@SAMEER
# EMAIL: SAMS44802@GMAIL.COM
# DATE: 18/08/2019
# PROGRAM: TO FIND THE AREA OF CIRCLE
radius = int(input('ENTER THE RADIUS OF CIRCLE'))
area = 2*3.14*radius
print("THE AREA OF CIRCLE IS " + str(area))