#CODED BY SAM @SAMEER
#EMAIL:SAMS44802@GMAIL.COM
#DATE:8/AUGT/2019
#PROGRAM:TO PERFROM VARIOUS CALCULATOR OPERATION
print(2+3)  #ADDITION
print(2-4)  #SUBTRACTION
print(3*4)  #MULTIPLICATION
print(2/4)  #float divsion
print(6/2)  #FLOAT DIVSION
print(4//2) #INTEGER DIVSION
print(2//4) #INTEGER DIVSION
print(6%2)  #MODULE
print(2**3) #EXPONENT
