# CODED BY SAM @SAMEER
# EMAIL:SAMS44802@GMAIL.COM
# DATE:19/10/2019
# PROGRAM: CONVERTING NEGATIVE NUMBERS TO POSITIVE
number = int(input("TYPE ANY NEGATIVE NUMBER :"))
number1 =  -number if number < 0 else number  # APPLYING MATHEMATICAL FORMULA
print(number1)