#  CODED BY SAM@SAMEER
#  EMAIL:SAMS44802@GAMIL.COM
#  DATE:12/09/2019
#  PROGRAM: DOCUMENTATION STRINGS


def func():
    """THIS PROGRAM WILL DISPLAY.
    """
    print("HELLO SAMEER")


print(func.__doc__)
func()