# CODED BY SAM@SAMEER
# EMAIL: SAMS44802@GMAIL.COM
# DATE: 18/08/2019
# PROGRAM: USING OF IF STATEMENT IN PYTHON
age = int(input('ENTER THE AGE'))
if age >= 21:
    print("U ARE SELECTED")
else:
    print("YOUR AGE IS BELOW 21")
