# CODED BY SAM@SAMEER
# EMAIL: SAMS44802@GMAIL.COM
# DATE: 17/08/2019
# PROGRAM: IMMUTABLE STRINGS
name = 'programmer'
# name[1] = 'R'
print(name.replace('r', 'R'))  # REPLACE FUNCTION WILL CREATE NEW STRING TO MAKE CHANGES
print(name)
