#  CODED BY SAM@SAMEER
#  EMAIL:SAMS44802@GAMIL.COM
#  DATE:22/09/2019
#  PROGRAM:TO OPEN AND CLOSE THE FILE
file = open("file2.txt", "wb")
print("FILE OPEN SUCCESSFULLY",)
print("FILE CLOSED SUCCESSFULLY")
file.close()