# CODED BY SAM@SAMEER
# EMAIL: SAMS44802@GMAIL.COM
# DATE: 20/08/2019
# PROGRAM: HOW TO USING BOTH OPERATORS AT THE SAME TIME
name = input('ENTER YOUR NAME')
age = int(input('ENTER YOUR AGE'))
if name[0] == "a" or name[0] == "A" and age >= 18:
    print("U CAN WATCH THE COCO MOVIE")
else:
    print("SORRY U CAN NOT WATCH NOT MOVIE")