# CODED BY SAM@SAMEER
# EMAIL: SAMS44802@GMAIL.COM
# DATE: 19/08/2019
# PROGRAM: USING OF PASS IN PYTHON
name = "sameer"
nam = input('ENTER THE NAME')
if name == nam:  # (==) IS USED TO COMPARISON BTW TWO
    print("NAME MATCHED")
else:
    pass  # PASS GIVES THE CONTROL TO ANOTHER STATEMENT
