# CODED BY SAM@SAMEER
# EMAIL: SAMS44802@GMAIL.COM
# DATE: 15/09/2019
# PROGRAM: PRINTING PARTICULAR CHARACTERS OF STRING BY GIVING STARTING INDEX AND END INDEX
name = "cluster university srinagar"
print(name[0:27])  # SYNTAX STRING_NAME[STARTING INDEX:END INDEX]
print(name[-27:27])  # PRINTING FIRST TO LAST CHARACTER
print(name[0:7])
print(name[7:18])
print(name[-27:-20])
print(name[:7])  # PRINTING FROM FIRST 7 CHARACTERS
print(name[0:-1])  # PRINTING FULL STRING EXCEPT LAST CHARACTER

