# CODED BY SAM@SAMEER
# EMAIL: SAMS44802@GMAIL.COM
# DATE:16/08/2019
# PROGRAM: STRING FUNCTIONS AND METHODS
name = "Programming LANGUAGE"
print(len(name))  # USING LEN FUNCTION TO COUNT THE CHARACTERS OF STRING
print(name.lower())  # MAKING ALL THE STRING INTO LOWER CASE
print(name.upper())  # MAKING ALL THE STRING INTO UPPER CASE
print(name.title())  # MAKING ONLY FIRST CHARACTER UPPERCASE
print(name.count("a"))  # USING COUNT METHOD TO FIND THE OCCURRENCE OF A CHARACTER
print(name.count("g"))  # OCCURRENCE OF  g ONLY
print(name.count("A"))

